-- CreateTable
CREATE TABLE "Profile" (
    "id" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "middleName" TEXT,
    "lastName" TEXT NOT NULL,
    "nameAsPerID" TEXT NOT NULL,
    "dateOfBirth" TEXT NOT NULL,
    "age" TEXT,
    "gender" TEXT NOT NULL,
    "maritalStatus" TEXT,
    "nationality" TEXT NOT NULL,
    "placeOfBirth" TEXT,
    "bloodGroup" TEXT,
    "permanentAddress" TEXT NOT NULL,
    "permanentCity" TEXT NOT NULL,
    "permanentState" TEXT NOT NULL,
    "permanentZip" TEXT NOT NULL,
    "currentAddress" TEXT,
    "currentCity" TEXT,
    "currentState" TEXT,
    "currentZip" TEXT,
    "primaryPhone" TEXT NOT NULL,
    "alternatePhone" TEXT,
    "email" TEXT NOT NULL,
    "communicationPreference" TEXT,
    "panNumber" TEXT,
    "aadhaarNumber" TEXT,
    "voterIdNumber" TEXT,
    "passportNumber" TEXT,
    "governmentIdFile" TEXT,
    "photoFile" TEXT,
    "signatureFile" TEXT,
    "bankName" TEXT,
    "accountNumber" TEXT,
    "ifscCode" TEXT,
    "creditCardNumber" TEXT,
    "cvv" TEXT,
    "monthlyIncome" TEXT,
    "annualIncome" TEXT,
    "incomeTaxPaid" TEXT,
    "occupation" TEXT,
    "employerName" TEXT,
    "employmentType" TEXT,
    "fatherName" TEXT,
    "motherName" TEXT,
    "spouseName" TEXT,
    "emergencyContactName" TEXT,
    "emergencyContactNumber" TEXT,
    "nomineeName" TEXT,
    "nomineeRelationship" TEXT,
    "nomineeDOB" TEXT,
    "healthInsuranceProvider" TEXT,
    "healthPolicyNumber" TEXT,
    "medicalHistory" TEXT,
    "allergies" TEXT,
    "ongoingMedications" TEXT,
    "dataConsent" BOOLEAN,
    "educationalQualification" TEXT,
    "formCategory" TEXT,
    "preferredLanguage" TEXT,
    "additionalNotes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Profile_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Profile_email_key" ON "Profile"("email");
